name: Purge jsDelivr Cache

on:
  push:
    branches:
      - main
    paths:
      - "bgp.js"

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr cache for bgp.js
        run: |
          echo "🚀 Purging jsDelivr cache..."
          curl -s -X GET "https://purge.jsdelivr.net/gh/we0030603/bgp/bgp.js"
          echo "✅ Done purging."
